language: php
php:
    - 7.0
    - nightly
script:
    - git clone https://github.com/krakjoe/apcu
    - cd apcu
    - phpize
    - ./configure
    - make
    - make install
    - cd ../
    - phpize
    - ./configure
    - make
    - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS=" -q --show-diff" make test
